#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on 21 May 2024

@author: ghart
"""

#------------------------------------------------------------------------------
# Statistic renaming
#------------------------------------------------------------------------------
# stats_mapping = {'max_branch_length':              'Max branch length',                     	# Branch Length
#                  'max_ex_branch_length':           'Max ext. branch length',                 	# Branch Length
#                  'max_in_branch_length':           'Max int. branch length',                 	# Branch Length
#                  'max_ratio_branch_length':        'Max ratio of branchs',                   	# Branch Length
#                  'mean_branch_length':             'Mean branch length',                     	# Branch Length
#                  'mean_ex_branch_length':          'Mean ext. branch length',               	# Branch Length
#                  'mean_in_branch_length':          'Mean int. branch length',               	# Branch Length
#                  'mean_ratio_branch_length':       'Mean ratio of branch lengths',              # Branch Length
#                  'median_branch_length':           'Median branch length',        	            # Branch Length
#                  'median_ex_branch_length':        'Median ext. branch length',               	# Branch Length
#                  'median_in_branch_length':        'Median int. branch length',               	# Branch Length
#                  'median_ratio_branch_length':     'Median ratio of branch lengths',            # Branch Length
#                  'min_branch_length':              'Min branch length',                       	# Branch Length
#                  'min_ex_branch_length':           'Min ext. branch length',                	# Branch Length
#                  'min_in_branch_length':           'Min int. branch length',                	# Branch Length
#                  'min_ratio_branch_length':        'Min ratio of branch lengths',             	# Branch Length
#                  'std_branch_length':              'Std. dev. branch length',                	# Branch Length
#                  'std_ex_branch_length':           'Std. dev. ext. branch length',            	# Branch Length
#                  'std_in_branch_length':           'Std. dev. int. branch length',              # Branch Length
#                  'std_ratio_branch_length':        'Std. dev. rotio of branch lengths',     	# Branch Length
#                  'B1':                             'B1',                                       	# Depth
#                  'B2':                             'B2',                                       	# Depth
#                  'max_height':                     'Maximum height',                           	# Depth
#                  'mean_height':                    'Mean height',                              	# Depth
#                  'min_height':                     'Minimum height',                           	# Depth
#                  'sackin':                         'Sackin index',                             	# Depth
#                  'sackin_var':                     'Sackin variance',                          	# Depth
#                  'cherries':                       'Cherries',                                 	# Local
#                  'double_cherries':                'Double cherries',                          	# Local
#                  'fourprong':                      'Fourprongs',                            	# Local
#                  'frac_basal':                     'Fraction basal',                        	# Local
#                  'mean_LBI':                       'Mean LBI',                                	# Local
#                  'mean_NN_dist':                   'Mean nearest neighbor dist. weighted',   	# Local
#                  'mean_NN_dist_unweighted':        'Mean nearest neighbor dist. unweighted',	# Local
#                  'pitchforks':                     'Pitchforks',                            	# Local
#                  'max_lineages':                   'Maximum lineages',                      	# LTT
#                  'mean_b_time':                    'Mean branching time',                   	# LTT
#                  'mean_s_time':                    'Mean sampling time',                    	# LTT
#                  'slope_1':                        'Slope 1',                               	# LTT
#                  'slope_2':                        'Slope 2',                               	# LTT
#                  'slope_ratio':                    'Slope ratio',                           	# LTT
#                  't_max_lineages':                 'Time of maximum lineages',              	# LTT
#                  'betweenness_max':                'Max betweenness',                       	# Network Science
#                  'closeness_max':                  'Max closeness weighted',                 	# Network Science
#                  'closeness_max_unweighted':       'Max closeness unweighted',              	# Network Science
#                  'diameter':                       'Diameter weighted',                     	# Network Science
#                  'diameter_unweighted':            'Diameter unweighted',                   	# Network Science
#                  'eigenvector_max':                'Eigenvector centrality weighted',       	# Network Science
#                  'eigenvector_max_unweighted':     'Eigenvector centrality unweighted',       	# Network Science
#                  'mean_path':                      'Mean path weighted',                    	# Network Science
#                  'mean_path_unweighted':           'Mean path unweighted',                  	# Network Science
#                  'eigen_gap':                      'Eigen gap weighted',                    	# Spectral
#                  'eigen_gap_unweighted':           'Eigen gap unweighted',                  	# Spectral
#                  'eigenvalue_max_adj':             'Max adj. eigenvalue weighted',          	# Spectral
#                  'eigenvalue_max_adj_unweighted':  'Max adj. eigenvalue unweighted',         	# Spectral
#                  'eigenvalue_max_dLap':            'Max dist. lap. eigenvalue weighted',    	# Spectral
#                  'eigenvalue_max_dLap_unweighted': 'Max dist. lap. eigenvalue unweighted',     	# Spectral
#                  'eigenvalue_max_lap':             'Max lap. eigenvalue weighted',          	# Spectral
#                  'eigenvalue_max_lap_unweighted':  'Max lap. eigenvalue unweighted',        	# Spectral
#                  'eigenvalue_min_adj':             'Min adj. eigenvalue weighted',          	# Spectral
#                  'eigenvalue_min_adj_unweighted':  'Min adj. eigenvalue unweighted',        	# Spectral
#                  'eigenvalue_min_lap':             'Min lap. eigenvalue weighted',          	# Spectral
#                  'eigenvalue_min_lap_unweighted':  'Min lap. eigenvalue unweighted',        	# Spectral
#                  'kurtosis':                       'Kurtosis weighted',                     	# Spectral
#                  'kurtosis_unweighted':            'Kurtosis unweighted',                   	# Spectral
#                  'skewness':                       'Skewness weighted',                     	# Spectral
#                  'skewness_unweighted':            'Skewness unweighted',                   	# Spectral
#                  'WD_ratio':                       'Maximum width-to-depth ratio',          	# Topology
#                  'colless':                        'Colless index',                         	# Topology
#                  'frac_imbalance':                 'Fration of imbalance',                  	# Topology
#                  'frac_ladder':                    'Fraction of ladders',                   	# Topology
#                  'max_dW':                         'Maximum midth change',                  	# Topology
#                  'max_ladder':                     'Maximum ladder size',                   	# Topology
#                  'mean_imbalance_ratio':           'Mean imbalance ratio'                   	# Topology
# } 

# stat_grouping = {'max_branch_length':              'Branch Length',
#                  'max_ex_branch_length':           'Branch Length',
#                  'max_in_branch_length':           'Branch Length',
#                  'max_ratio_branch_length':        'Branch Length',
#                  'mean_branch_length':             'Branch Length',
#                  'mean_ex_branch_length':          'Branch Length',
#                  'mean_in_branch_length':          'Branch Length',
#                  'mean_ratio_branch_length':       'Branch Length',
#                  'median_branch_length':           'Branch Length',
#                  'median_ex_branch_length':        'Branch Length',
#                  'median_in_branch_length':        'Branch Length',
#                  'median_ratio_branch_length':     'Branch Length',
#                  'min_branch_length':              'Branch Length',
#                  'min_ex_branch_length':           'Branch Length',
#                  'min_in_branch_length':           'Branch Length',
#                  'min_ratio_branch_length':        'Branch Length',
#                  'std_branch_length':              'Branch Length',
#                  'std_ex_branch_length':           'Branch Length',
#                  'std_in_branch_length':           'Branch Length',
#                  'std_ratio_branch_length':        'Branch Length',
#                  'B1':                             'Depth',
#                  'B2':                             'Depth',
#                  'max_height':                     'Depth',
#                  'mean_height':                    'Depth',
#                  'min_height':                     'Depth',
#                  'sackin':                         'Depth',
#                  'sackin_var':                     'Depth',
#                  'cherries':                       'Local',
#                  'double_cherries':                'Local',
#                  'fourprong':                      'Local',
#                  'frac_basal':                     'Local',
#                  'mean_LBI':                       'Local',
#                  'mean_NN_dist':                   'Local',
#                  'mean_NN_dist_unweighted':        'Local',
#                  'pitchforks':                     'Local',
#                  'max_lineages':                   'LTT',
#                  'mean_b_time':                    'LTT',
#                  'mean_s_time':                    'LTT',
#                  'slope_1':                        'LTT',
#                  'slope_2':                        'LTT',
#                  'slope_ratio':                    'LTT',
#                  't_max_lineages':                 'LTT',
#                  'betweenness_max':                'Network Science',
#                  'closeness_max':                  'Network Science',
#                  'closeness_max_unweighted':       'Network Science',
#                  'diameter':                       'Network Science',
#                  'diameter_unweighted':            'Network Science',
#                  'eigenvector_max':                'Network Science',
#                  'eigenvector_max_unweighted':     'Network Science',
#                  'mean_path':                      'Network Science',
#                  'mean_path_unweighted':           'Network Science',
#                  'eigen_gap':                      'Spectral',
#                  'eigen_gap_unweighted':           'Spectral',
#                  'eigenvalue_max_adj':             'Spectral',
#                  'eigenvalue_max_adj_unweighted':  'Spectral',
#                  'eigenvalue_max_dLap':            'Spectral',
#                  'eigenvalue_max_dLap_unweighted': 'Spectral',
#                  'eigenvalue_max_lap':             'Spectral',
#                  'eigenvalue_max_lap_unweighted':  'Spectral',
#                  'eigenvalue_min_adj':             'Spectral',
#                  'eigenvalue_min_adj_unweighted':  'Spectral',
#                  'eigenvalue_min_lap':             'Spectral',
#                  'eigenvalue_min_lap_unweighted':  'Spectral',
#                  'kurtosis':                       'Spectral',
#                  'kurtosis_unweighted':            'Spectral',
#                  'skewness':                       'Spectral',
#                  'skewness_unweighted':            'Spectral',
#                  'WD_ratio':                       'Topology',
#                  'colless':                        'Topology',
#                  'frac_imbalance':                 'Topology',
#                  'frac_ladder':                    'Topology',
#                  'max_dW':                         'Topology',
#                  'max_ladder':                     'Topology',
#                  'mean_imbalance_ratio':           'Topology'
#                  }

group_colors = {'Branch Length': 'b',
                'Depth': 'g',
                'Local': 'r',
                'LTT': 'c',
                'Network Science': 'm',
                'Spectral': 'y',
                'Topology': 'b'
                }

param_mapping = {'birth_rate': 'Birth rate',
                 'death_rate': 'Death rate',
                 'n_leaves':   'Num. leaves',
                 'R0': '$R_0$',
                 'contacts': 'Number\nof\ncontacts',
                 'infection_duration': 'Infectious\nduration',
                 'population_size': 'Total\npop.\nsize',
                 'sample_fraction': 'Sample\ncoverage',
                 'sample_time': 'Sample\ndelay',
                 'R_eff': '$R_e$',
                 'cum_incidence': 'Cumulative\nincidence',
                 'incidence': 'Incidence',
                 'prevalence': 'Prevalence'
                 }

stats_mapping = {'max_branch_length':              {'group': 'Branch Length',
                                                    'displayName': 'Max branch length',
                                                    'functionName': 'BL_calculate_max',
                                                    'internalName': 'max_branch_length',
                                                    'kwargs': {}},
                 'max_ex_branch_length':           {'group': 'Branch Length',
                                                    'displayName': 'Max ex. branch length',
                                                    'functionName': 'BL_calculate_external_max',
                                                    'internalName': 'max_ex_branch_length',
                                                    'kwargs': {}},
                 'max_in_branch_length':           {'group': 'Branch Length',
                                                    'displayName': 'Max in. branch length',
                                                    'functionName': 'BL_calculate_internal_max',
                                                    'internalName': 'max_in_branch_length',
                                                    'kwargs': {}},
                 'max_ratio_branch_length':        {'group': 'Branch Length',
                                                    'displayName': 'Max ratio of branchs',
                                                    'functionName': 'BL_calculate_ratio_max',
                                                    'internalName': 'max_ratio_branch_length',
                                                    'kwargs': {}},
                 'mean_branch_length':             {'group': 'Branch Length',
                                                    'displayName': 'Mean branch length',
                                                    'functionName': 'BL_calculate_mean',
                                                    'internalName': 'mean_branch_length',
                                                    'kwargs': {}},
                 'mean_ex_branch_length':          {'group': 'Branch Length',
                                                    'displayName': 'Mean ex. branch length',
                                                    'functionName': 'BL_calculate_external_mean',
                                                    'internalName': 'mean_ex_branch_length',
                                                    'kwargs': {}},
                 'mean_in_branch_length':          {'group': 'Branch Length',
                                                    'displayName': 'Mean in. branch length',
                                                    'functionName': 'BL_calculate_internal_mean',
                                                    'internalName': 'mean_in_branch_length',
                                                    'kwargs': {}},
                 'mean_ratio_branch_length':       {'group': 'Branch Length',
                                                    'displayName': 'Mean ratio of branchs',
                                                    'functionName': 'BL_calculate_ratio_mean',
                                                    'internalName': 'mean_ratio_branch_length',
                                                    'kwargs': {}},
                 'median_branch_length':           {'group': 'Branch Length',
                                                    'displayName': 'Median branch length',
                                                    'functionName': 'BL_calculate_median',
                                                    'internalName': 'median_branch_length',
                                                    'kwargs': {}},
                 'median_ex_branch_length':        {'group': 'Branch Length',
                                                    'displayName': 'Median ex. branch length',
                                                    'functionName': 'BL_calculate_external_median',
                                                    'internalName': 'median_ex_branch_length',
                                                    'kwargs': {}},
                 'median_in_branch_length':        {'group': 'Branch Length',
                                                    'displayName': 'Median in. branch length',
                                                    'functionName': 'BL_calculate_internal_median',
                                                    'internalName': 'median_in_branch_length',
                                                    'kwargs': {}},
                 'median_ratio_branch_length':     {'group': 'Branch Length',
                                                    'displayName': 'Median ratio of branchs',
                                                    'functionName': 'BL_calculate_ratio_median',
                                                    'internalName': 'median_ratio_branch_length',
                                                    'kwargs': {}},
                 'min_branch_length':              {'group': 'Branch Length',
                                                    'displayName': 'Min branch length',
                                                    'functionName': 'BL_calculate_min',
                                                    'internalName': 'min_branch_length',
                                                    'kwargs': {}},
                 'min_ex_branch_length':           {'group': 'Branch Length',
                                                    'displayName': 'Min ex. branch length',
                                                    'functionName': 'BL_calculate_external_min',
                                                    'internalName': 'min_ex_branch_length',
                                                    'kwargs': {}},
                 'min_in_branch_length':           {'group': 'Branch Length',
                                                    'displayName': 'Min in. branch length',
                                                    'functionName': 'BL_calculate_internal_min',
                                                    'internalName': 'min_in_branch_length',
                                                    'kwargs': {}},
                 'min_ratio_branch_length':        {'group': 'Branch Length',
                                                    'displayName': 'Min ratio of branchs',
                                                    'functionName': 'BL_calculate_ratio_min',
                                                    'internalName': 'min_ratio_branch_length',
                                                    'kwargs': {}},
                 'std_branch_length':              {'group': 'Branch Length',
                                                    'displayName': 'Std. dev. branch length',
                                                    'functionName': 'BL_calculate_std',
                                                    'internalName': 'std_branch_length',
                                                    'kwargs': {}},
                 'std_ex_branch_length':           {'group': 'Branch Length',
                                                    'displayName': 'Std. dev. ex. branch length',
                                                    'functionName': 'BL_calculate_external_std',
                                                    'internalName': 'std_ex_branch_length',
                                                    'kwargs': {}},
                 'std_in_branch_length':           {'group': 'Branch Length',
                                                    'displayName': 'Std. dev. in. branch length',
                                                    'functionName': 'BL_calculate_internal_std',
                                                    'internalName': 'std_in_branch_length',
                                                    'kwargs': {}},
                 'std_ratio_branch_length':        {'group': 'Branch Length',
                                                    'displayName': 'Std. dev. ratio of branchs',
                                                    'functionName': 'BL_calculate_ratio_std',
                                                    'internalName': 'std_ratio_branch_length',
                                                    'kwargs': {}},
                 'B1':                             {'group': 'Depth',
                                                    'displayName': 'B1',
                                                    'functionName': 'top_calculate_B1',
                                                    'internalName': 'B1',
                                                    'kwargs': {}},
                 'B2':                             {'group': 'Depth',
                                                    'displayName': 'B2',
                                                    'functionName': 'top_calculate_B2',
                                                    'internalName': 'B2',
                                                    'kwargs': {}},
                 'max_height':                     {'group': 'Depth',
                                                    'displayName': 'Maximum height',
                                                    'functionName': 'tree_height_calculate_max',
                                                    'internalName': 'max_height',
                                                    'kwargs': {}},
                 'mean_height':                    {'group': 'Depth',
                                                    'displayName': 'Mean height',
                                                    'functionName': 'tree_height_calculate_mean',
                                                    'internalName': 'mean_height',
                                                    'kwargs': {}},
                 'min_height':                     {'group': 'Depth',
                                                    'displayName': 'Minimum height',
                                                    'functionName': 'tree_height_calculate_min',
                                                    'internalName': 'min_height',
                                                    'kwargs': {}},
                 'sackin':                         {'group': 'Depth',
                                                    'displayName': 'Sackin index',
                                                    'functionName': 'top_calculate_sackin',
                                                    'internalName': 'sackin',
                                                    'kwargs': {}},
                 'sackin_var':                     {'group': 'Depth',
                                                    'displayName': 'Sackin variance',
                                                    'functionName': 'top_calculate_sackin_var',
                                                    'internalName': 'sackin_var',
                                                    'kwargs': {}},
                 'cherries':                       {'group': 'Local',
                                                    'displayName': 'Cherries',
                                                    'functionName': 'smallConfig_calculate_cherries',
                                                    'internalName': 'cherries',
                                                    'kwargs': {}},
                 'double_cherries':                {'group': 'Local',
                                                    'displayName': 'Double cherries',
                                                    'functionName': 'smallConfig_calculate_double_cherries',
                                                    'internalName': 'double_cherries',
                                                    'kwargs': {}},
                 'fourprong':                      {'group': 'Local',
                                                    'displayName': 'Fourprongs',
                                                    'functionName': 'smallConfig_calculate_fourprong',
                                                    'internalName': 'fourprong',
                                                    'kwargs': {}},
                 'frac_basal':                     {'group': 'Local',
                                                    'displayName': 'Fraction basal',
                                                    'functionName': 'local_calculate_frac_basal',
                                                    'internalName': 'frac_basal',
                                                    'kwargs': {}},
                 'mean_LBI':                       {'group': 'Local',
                                                    'displayName': 'Mean LBI',
                                                    'functionName': 'local_calculate_LBI_mean',
                                                    'internalName': 'mean_LBI',
                                                    'kwargs': {}},
                 'mean_NN_dist':                   {'group': 'Local',
                                                    'displayName': 'Mean nearest neigbor dist. weighted',
                                                    'functionName': 'mean_NN_distance',
                                                    'internalName': 'mean_NN_dist',
                                                    'kwargs': {}},
                 'mean_NN_dist_unweighted':        {'group': 'Local',
                                                    'displayName': 'Mean nearest neigbor dist. unweighted',
                                                    'functionName': 'mean_NN_distance',
                                                    'internalName': 'mean_NN_dist_topology',
                                                    'kwargs': {'topology_only': True}},
                 'pitchforks':                     {'group': 'Local',
                                                    'displayName': 'Pitchforks',
                                                    'functionName': 'smallConfig_calculate_pitchforks',
                                                    'internalName': 'pitchforks',
                                                    'kwargs': {}},
                 'max_lineages':                   {'group': 'LTT',
                                                    'displayName': 'Maximum lineages',
                                                    'functionName': 'LTT_calculate_max_lineages',
                                                    'internalName': 'max_lineages',
                                                    'kwargs': {}},
                 'mean_b_time':                    {'group': 'LTT',
                                                    'displayName': 'Mean branching time',
                                                    'functionName': 'LTT_calculate_mean_b_time',
                                                    'internalName': 'mean_b_time',
                                                    'kwargs': {}},
                 'mean_s_time':                    {'group': 'LTT',
                                                    'displayName': 'Mean sampling time',
                                                    'functionName': 'LTT_calculate_mean_s_time',
                                                    'internalName': 'mean_s_time',
                                                    'kwargs': {}},
                 'slope_1':                        {'group': 'LTT',
                                                    'displayName': 'Slope 1',
                                                    'functionName': 'LTT_calculate_slope_1',
                                                    'internalName': 'slope_1',
                                                    'kwargs': {}},
                 'slope_2':                        {'group': 'LTT',
                                                    'displayName': 'Slope 2',
                                                    'functionName': 'LTT_calculate_slope_2',
                                                    'internalName': 'slope_2',
                                                    'kwargs': {}},
                 'slope_ratio':                    {'group': 'LTT',
                                                    'displayName': 'Slope ratio',
                                                    'functionName': 'LTT_calculate_slope_ratio',
                                                    'internalName': 'slope_ratio',
                                                    'kwargs': {}},
                 't_max_lineages':                 {'group': 'LTT',
                                                    'displayName': 'Time of maximum lineages',
                                                    'functionName': 'LTT_calculate_t_max_lineages',
                                                    'internalName': 't_max_lineages',
                                                    'kwargs': {}},
                 'betweenness_max':                {'group': 'Network Science',
                                                    'displayName': 'Maximum betweenness',
                                                    'functionName': 'netSci_calculate_betweenness_max',
                                                    'internalName': 'betweenness_max',
                                                    'kwargs': {}},
                 'closeness_max':                  {'group': 'Network Science',
                                                    'displayName': 'Maximum closeness weighted',
                                                    'functionName': 'netSci_calculate_closeness_max',
                                                    'internalName': 'closeness_max',
                                                    'kwargs': {}},
                 'closeness_max_unweighted':       {'group': 'Network Science',
                                                    'displayName': 'Maximum closeness unweighted',
                                                    'functionName': 'netSci_calculate_closeness_max',
                                                    'internalName': 'closeness_max_topology',
                                                    'kwargs': {'topology_only': True}},
                 'diameter':                       {'group': 'Network Science',
                                                    'displayName': 'Diameter weighted',
                                                    'functionName': 'netSci_calculate_diameter',
                                                    'internalName': 'diameter',
                                                    'kwargs': {}},
                 'diameter_unweighted':            {'group': 'Network Science',
                                                    'displayName': 'Diameter unweighted',
                                                    'functionName': 'netSci_calculate_diameter',
                                                    'internalName': 'diameter_topology',
                                                    'kwargs': {'topology_only': True}},
                 'eigenvector_max':                {'group': 'Network Science',
                                                    'displayName': 'Eigenvector centrality weighted',
                                                    'functionName': 'netSci_calculate_eigen_centrality_max',
                                                    'internalName': 'eigenvector_max',
                                                    'kwargs': {}},
                 'eigenvector_max_unweighted':     {'group': 'Network Science',
                                                    'displayName': 'Eigenvector centrality unweighted',
                                                    'functionName': 'netSci_calculate_eigen_centrality_max',
                                                    'internalName': 'eigenvector_max_topology',
                                                    'kwargs': {'topology_only': True}},
                 'mean_path':                      {'group': 'Network Science',
                                                    'displayName': 'Mean path weighted',
                                                    'functionName': 'netSci_calculate_mean_path',
                                                    'internalName': 'mean_path',
                                                    'kwargs': {}},
                 'mean_path_unweighted':           {'group': 'Network Science',
                                                    'displayName': 'Mean path unweighted',
                                                    'functionName': 'netSci_calculate_mean_path',
                                                    'internalName': 'mean_path_topology',
                                                    'kwargs': {'topology_only': True}},
                 'eigen_gap':                      {'group': 'Spectral',
                                                    'displayName': 'Eigen gap weighted',
                                                    'functionName': 'spectral_calculate_eigen_gap',
                                                    'internalName': 'eigen_gap',
                                                    'kwargs': {'topology_only': False}},
                 'eigen_gap_unweighted':           {'group': 'Spectral',
                                                    'displayName': 'Eigen gap unweighted',
                                                    'functionName': 'spectral_calculate_eigen_gap',
                                                    'internalName': 'eigen_gap_unweighted',
                                                    'kwargs': {'topology_only': True}},
                 'eigenvalue_max_adj':             {'group': 'Spectral',
                                                    'displayName': 'Max adj. eigenvalue weighted',
                                                    'functionName': 'spectral_calculate_max_adj_eigen',
                                                    'internalName': 'eigenvalue_max_adj',
                                                    'kwargs': {'topology_only': False}},
                 'eigenvalue_max_adj_unweighted':  {'group': 'Spectral',
                                                    'displayName': 'Max adj. eigenvalue unweighted',
                                                    'functionName': 'spectral_calculate_max_adj_eigen',
                                                    'internalName': 'eigenvalue_max_adj_unweighted',
                                                    'kwargs': {'topology_only': True}},
                 'eigenvalue_max_dLap':            {'group': 'Spectral',
                                                    'displayName': 'Max dist. lap. eigenvalue weighted',
                                                    'functionName': 'spectral_calculate_max_distLap_eigen',
                                                    'internalName': 'eigenvalue_max_dLap',
                                                    'kwargs': {'topology_only': False}},
                 'eigenvalue_max_dLap_unweighted': {'group': 'Spectral',
                                                    'displayName': 'Max dist. lap. eigenvalue unweighted',
                                                    'functionName': 'spectral_calculate_max_distLap_eigen',
                                                    'internalName': 'eigenvalue_max_dLap_unweighted',
                                                    'kwargs': {'topology_only': True}},
                 'eigenvalue_max_lap':             {'group': 'Spectral',
                                                    'displayName': 'Max lap. eigenvalue weighted',
                                                    'functionName': 'spectral_calculate_max_lap_eigen',
                                                    'internalName': 'eigenvalue_max_lap',
                                                    'kwargs': {'topology_only': False}},
                 'eigenvalue_max_lap_unweighted':  {'group': 'Spectral',
                                                    'displayName': 'Max lap. eigenvalue unweighted',
                                                    'functionName': 'spectral_calculate_max_lap_eigen',
                                                    'internalName': 'eigenvalue_max_lap_unweighted',
                                                    'kwargs': {'topology_only': True}},
                 'eigenvalue_min_adj':             {'group': 'Spectral',
                                                    'displayName': 'Min adj. eigenvalue weighted',
                                                    'functionName': 'spectral_calculate_min_adj_eigen',
                                                    'internalName': 'eigenvalue_min_adj',
                                                    'kwargs': {'topology_only': False}},
                 'eigenvalue_min_adj_unweighted':  {'group': 'Spectral',
                                                    'displayName': 'Min adj. eigenvalue unweighted',
                                                    'functionName': 'spectral_calculate_min_adj_eigen',
                                                    'internalName': 'eigenvalue_min_adj_unweighted',
                                                    'kwargs': {'topology_only': True}},
                 'eigenvalue_min_lap':             {'group': 'Spectral',
                                                    'displayName': 'Min lap. eigenvalue weighted',
                                                    'functionName': 'spectral_calculate_min_lap_eigen',
                                                    'internalName': 'eigenvalue_min_lap',
                                                    'kwargs': {'topology_only': False}},
                 'eigenvalue_min_lap_unweighted':  {'group': 'Spectral',
                                                    'displayName': 'Min lap. eigenvalue unweighted',
                                                    'functionName': 'spectral_calculate_min_lap_eigen',
                                                    'internalName': 'eigenvalue_min_lap_unweighted',
                                                    'kwargs': {'topology_only': True}},
                 'kurtosis':                       {'group': 'Spectral',
                                                    'displayName': 'Kurtosis weighted',
                                                    'functionName': 'spectral_calculate_kurtosis',
                                                    'internalName': 'kurtosis',
                                                    'kwargs': {'topology_only': False}},
                 'kurtosis_unweighted':            {'group': 'Spectral',
                                                    'displayName': 'Kurtosis unweighted',
                                                    'functionName': 'spectral_calculate_kurtosis',
                                                    'internalName': 'kurtosis_unweighted',
                                                    'kwargs': {'topology_only': True}},
                 'skewness':                       {'group': 'Spectral',
                                                    'displayName': 'Skewness weighted',
                                                    'functionName': 'spectral_calculate_skewness',
                                                    'internalName': 'skewness',
                                                    'kwargs': {'topology_only': False}},
                 'skewness_unweighted':            {'group': 'Spectral',
                                                    'displayName': 'Skewness unweighted',
                                                    'functionName': 'spectral_calculate_skewness',
                                                    'internalName': 'skewness_unweighted',
                                                    'kwargs': {'topology_only': True}},
                 'WD_ratio':                       {'group': 'Topology',
                                                    'displayName': 'Maximum width-to-depth ratio',
                                                    'functionName': 'top_calculate_WD_ratio',
                                                    'internalName': 'WD_ratio',
                                                    'kwargs': {}},
                 'colless':                        {'group': 'Topology',
                                                    'displayName': 'Colless index',
                                                    'functionName': 'top_calculate_colless',
                                                    'internalName': 'colless',
                                                    'kwargs': {}},
                 'frac_imbalance':                 {'group': 'Topology',
                                                    'displayName': 'Fration of imbalance',
                                                    'functionName': 'top_calculate_frac_imbalance',
                                                    'internalName': 'frac_imbalance',
                                                    'kwargs': {}},
                 'frac_ladder':                    {'group': 'Topology',
                                                    'displayName': 'Fraction of ladders',
                                                    'functionName': 'top_calculate_frac_ladder',
                                                    'internalName': 'frac_ladder',
                                                    'kwargs': {}},
                 'max_dW':                         {'group': 'Topology',
                                                    'displayName': 'Maximum width change',
                                                    'functionName': 'top_calculate_max_dW',
                                                    'internalName': 'max_dW',
                                                    'kwargs': {}},
                 'max_ladder':                     {'group': 'Topology',
                                                    'displayName': 'Maximum ladder size',
                                                    'functionName': 'top_calculate_max_ladder',
                                                    'internalName': 'max_ladder',
                                                    'kwargs': {}},
                 'mean_imbalance_ratio':           {'group': 'Topology',
                                                    'displayName': 'Mean imbalance ratio',
                                                    'functionName': 'top_calculate_mean_imbalance_ratio',
                                                    'internalName': 'mean_imbalance_ratio',
                                                    'kwargs': {}}
                 }